{% set name = "django-pyodbc-azure" %}
{% set version = "2.0.6.1" %}
{% set sha256 = "2920a03522ad8d99195637192601768b33146555f45077be0f0281eb7b44215a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/michiya/django-pyodbc-azure/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - pyodbc >=3.0
    - django >=2.0.6,<2.1

test:
  imports:
    - sql_server
    - sql_server.pyodbc

about:
  home: https://github.com/michiya/django-pyodbc-azure
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Django backend for Microsoft SQL Server and Azure SQL Database using pyodbc'
  description: |
    django-pyodbc-azure is a refined fork of django-pyodbc, a Django
    Microsoft SQL Server external DB backend that uses ODBC by employing the
    pyodbc library. It supports Microsoft SQL Server and Azure SQL Database.
  dev_url: https://github.com/michiya/django-pyodbc-azure

extra:
  recipe-maintainers:
    - wil
