{% set version = "2.1.0.0" %}

package:
  name: django-pyodbc-azure
  version: {{ version }}

source:
  url: https://github.com/michiya/django-pyodbc-azure/archive/{{ version }}.zip
  sha256: 0bdc974ce063240e2357afababb76de9e4e416490b2e8b141c64e4959cede975

build:
  noarch: python
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python >=3
    - pyodbc >=3.0
    - django >=2.1.0,<2.2

test:
  imports:
    - sql_server
    - sql_server.pyodbc

about:
  home: https://github.com/michiya/django-pyodbc-azure
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Django backend for Microsoft SQL Server and Azure SQL Database using pyodbc'
  description: |
    django-pyodbc-azure is a refined fork of django-pyodbc, a Django
    Microsoft SQL Server external DB backend that uses ODBC by employing the
    pyodbc library. It supports Microsoft SQL Server and Azure SQL Database.
  dev_url: https://github.com/michiya/django-pyodbc-azure

extra:
  recipe-maintainers:
    - roccqqck
