travis:
  secure:
    BINSTAR_TOKEN: igHivExav4T0oOCrdPcUPZMbbA/6UF3kbaE6iHAIR7AKGU8GpSmJR5oyUZFu/WAIzXdnEhl6IkleyfPD6wYRDTrw+MvSJ7zkkYtb26uyZesb+DW+10NYWImw0rsQsm/w+Z8zvWusYDDH8Lf49JY2Cpcb3Bo9cnwZl5cOuNPiQGsTKJEkmOhXP6+7aNMkdLJJgENuL97dRkJF8A+Oh2HQmaboDvoym318I5qCwFQcZflhsS+r+6dQffA/qjcodcP+QdPQ6Dn/uJFkG1KiEsPkUjWVB2WD7ZZgKsmGUUiunQr0LdlxpRIV9hm2Ls3+DcbhinNpA/loHbLou93xtds9+RjGHnqvTx5qywbfyI4iu3KlzzUiJxltQE0/KQ5c5gAXhamRH6POVE7L3HmZ+vdUcD5F70wJYEo1/8rOTHKwXr9fbvWycEmFhnMZ1DvXMb6Mi3I9k2Ki3Ptr+jB0vzOHwY7ppw0LsiRc2OVpU4WRrNeVzHENwruS+tvrJMMweKeQ8+rQfbvBYZKTYXQ+N1PbZUDBpjIw9AAKCmqzFZsyLSwdzCiE84xlm0XpbBdY2AFoicvRSlKwNOmgvsvFP9lNspWQewdNZad8k+QuOcx4qHCisiCiMLMUcufPrbJmxAML01E53AIdwT+xpvT98z3HNEIrdljqhLH3s4namBohNRc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
